require: rubocop-rspec

AllCops:
  DisplayCopNames: true

## Style

Style/Documentation:
  Enabled: false
Style/SingleSpaceBeforeFirstArg:
  Enabled: false
Style/AccessorMethodName:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/WordArray:
  Enabled: false

Style/GuardClause:
  Enabled: true
Style/MethodCalledOnDoEndBlock:
  Enabled: true
Style/CollectionMethods:
  Enabled: true

Style/TrivialAccessors:
  ExactNameMatch: true

Style/PredicateName:
  NamePrefix:
    - is_
    - have_
  NamePrefixBlacklist:
    - is_
    - have_

Style/StringLiterals:
  EnforcedStyle: double_quotes

## Metrics

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 10

## RSpec

RSpec/DescribeClass:
  Enabled: false
RSpec/DescribedClass:
  Enabled: true
RSpec/DescribeMethod:
  Enabled: false
RSpec/FilePath:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false
