inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  DisplayCopNames: true

Layout/SpaceBeforeFirstArg:
  Enabled: false

## Style

Style/Documentation:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/WordArray:
  Enabled: false

Style/GuardClause:
  Enabled: true
Style/MethodCalledOnDoEndBlock:
  Enabled: true
Style/CollectionMethods:
  Enabled: true

Style/TrivialAccessors:
  ExactNameMatch: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

## Metrics

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Naming/AccessorMethodName:
  Enabled: false
Naming/PredicateName:
  NamePrefix:
    - is_
    - have_
  NamePrefixBlacklist:
    - is_
    - have_

## RSpec

RSpec/DescribeClass:
  Enabled: false
RSpec/DescribedClass:
  Enabled: true
RSpec/DescribeMethod:
  Enabled: false
RSpec/FilePath:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExpectActual:
  Enabled: false
