#!/usr/bin/env ruby

require 'mac_setup'

DEFAULT_CONFIG_PATH = '~/.mac_setup.yml'

config_path = ARGV[0] || File.expand_path(DEFAULT_CONFIG_PATH)

if File.exist?(config_path)
  MacSetup.install(config_path)
else
  puts "You must specify a path to config file or create one at #{DEFAULT_CONFIG_PATH}"
end
