#!/usr/bin/env ruby

require "mac_setup"

command = ARGV.shift
options = ARGV.select { |arg| arg.start_with?("--") }
config_path = (ARGV - options).first || File.expand_path(DEFAULT_CONFIG_PATH)

case command
when "bootstrap"
  MacSetup.bootstrap(ARGV.take(2))
when "install"
  # config_path = (ARGV - options)[0] || File.expand_path(DEFAULT_CONFIG_PATH)

  # if File.exist?(config_path)
    MacSetup.install # (config_path, options)
  # else
  #   puts "You must specify a path to config file or create one at #{DEFAULT_CONFIG_PATH}"
  # end
when "encrypt"
  MacSetup.encrypt
else
  puts "Unknown command: #{command}"
  puts "Version: #{MacSetup::VERSION}"
end
