#!/usr/bin/env ruby

require "mac_setup"

DEFAULT_CONFIG_PATH = "~/.mac_setup/config.yml"

command = ARGV.shift
options = ARGV.select { |arg| arg.start_with?("--") }

case command
when "bootstrap"
  MacSetup.bootstrap(ARGV[0])
when "install"
  config_path = (ARGV - options)[0] || File.expand_path(DEFAULT_CONFIG_PATH)

  if File.exist?(config_path)
    MacSetup.install(config_path, options)
  else
    puts "You must specify a path to config file or create one at #{DEFAULT_CONFIG_PATH}"
  end
else
  puts "Unknown command: #{command}"
end
